### ISSUE TITLE
Project discussion

### ISSUE THREAD

**Issue by WieFel** [TinyCommunity/tinycolor2#1]
So let's discuss how we proceed from here @calvintam236.

**Comment by calvintam236** [comment]
@WieFel
1. can you set my role in the organization to admin? I can’t even write to the repo 😆
2. let’s setup a Discussion tab for feature requests and support thread and leave issues for bug reports only?
3. I have posted comments to the existing PR from the main repo and asks if they can make a PR over here.

**Comment by WieFel** [comment]
Done!

**Comment by dsyrstad** [comment]
Perhaps move this over to the Discussions tab?

**Comment by calvintam236** [comment]
@WieFel There is a button to convert this to discussion. Anyways, continue this chat on #2 and locking this.

**Comment by WieFel** [comment]
Sorry, didn't know that. Never used discussions before 😬
