### ISSUE TITLE
setAlpha and setOpacity have no effect

### ISSUE THREAD

**Issue by nfriend** [TinyCommunity/tinycolor2#3]
### Summary

The `setAlpha` and `setOpacity` methods don't seem to have any effect on the `TinyColor` instance.

### Possible cause

Looking at the source, I believe this is because these methods [are defined like this](https://github.com/FooStudio/tinycolor/blob/717a603a6e3a35b693e8b0dab15384a954067034/lib/tinycolor.dart#L59-L62):

```js
TinyColor setAlpha(int alpha) {
  _color.withAlpha(alpha);
  return this;
}
```

However, the `withAlpha` method [returns a _new_ `Color` instance](https://api.flutter.dev/flutter/dart-ui/Color/withAlpha.html):

> Returns a new color that matches this color with the alpha channel replaced with a (which ranges from 0 to 255).

so this doesn't actually change `_color`.

### Context

This bug was originally submitted to https://github.com/FooStudio/tinycolor/issues/14 and was copied here.

**Comment by TNorbury** [comment]
I can take a look at this!

**Comment by dsyrstad** [comment]
Should be `_color = _color.withAlpha(alpha);`
