### ISSUE TITLE
Most setters should update internal color value and return this

### ISSUE THREAD

**Issue by calvintam236** [TinyCommunity/tinycolor2#38]
**Describe the bug**
Upon checking from the [original](https://github.com/bgrins/TinyColor/blob/master/tinycolor.js#L214-L224) code, setters update the internal color value and return its own reference.
Yet, most of the setters of the port of this library do not update and return a new `TinyColor`. See [here](https://github.com/TinyCommunity/tinycolor2/blob/master/lib/src/tinycolor.dart#L71-L76) for example.

This is an inconsistent behavior that should be fixed. (`.setAlpha()` & `.setOpacity()` is behaving correctly.)

**Expected behavior**
After calling any setters, `.color` property should be updated and return the updated `this` instead of creating another `TinyColor`.

**Comment by calvintam236** [comment]
Alternatively, we can make it return a new `TinyColor` instance on all setters. This can maintain whatever instance you created earlier does not change after you call any of the setters.

@WieFel which way is better?

**Comment by WieFel** [comment]
@calvintam236 yes, I think it should keep the same behaviour as the original library. Thus, we should change `lighten` etc. to modify the internal color value and return `this`.
