### ISSUE TITLE
v2.0.1

### ISSUE THREAD

**Issue by calvintam236** [TinyCommunity/tinycolor2#46]
@WieFel I believe the `master` branch is ready for v2.0.1.

Can you check and make a new release if that’s all good?

Note: please update changelog date before publish.

**Comment by WieFel** [comment]
@calvintam236 sorry, am currently very busy with work. Could take some time until I can have a look.
If you want you can go ahead and create PR with changelog changes etc. and i will approve

**Comment by calvintam236** [comment]
@WieFel I would like to get #35 merged before releasing v2.0.1. Do you think you can take a look this weekend? If not, we can do it as-is at `master`.

I have created draft release at [here](https://github.com/TinyCommunity/tinycolor2/releases/tag/untagged-15ac35a123ea9bb64a8f).

**Comment by WieFel** [comment]
@calvintam236 Just approved PR

**Comment by calvintam236** [comment]
@WieFel Looks like your pub.dev credentials are expired… Can you update them in the secrets?

**Comment by calvintam236** [comment]
https://github.com/k-paxian/dart-package-publisher#inputs

**Comment by WieFel** [comment]
Done.
Sorry for the delay. Please report back if it works now

**Comment by calvintam236** [comment]
Hooray, it succeed!
